//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetDemo {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetDemo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetDemo() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetDemo.NetDemo", typeof(NetDemo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button5_Image {
            get {
                object obj = ResourceManager.GetObject("button5.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button60_Image {
            get {
                object obj = ResourceManager.GetObject("button60.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button66_Image {
            get {
                object obj = ResourceManager.GetObject("button66.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button67_Image {
            get {
                object obj = ResourceManager.GetObject("button67.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button68_Image {
            get {
                object obj = ResourceManager.GetObject("button68.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button7_Image {
            get {
                object obj = ResourceManager.GetObject("button7.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button70_Image {
            get {
                object obj = ResourceManager.GetObject("button70.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button8_Image {
            get {
                object obj = ResourceManager.GetObject("button8.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Bitmap button9_Image {
            get {
                object obj = ResourceManager.GetObject("button9.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {X=123,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point deviceOper_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("deviceOper.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordIDNoDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordIDNoDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordLibImageDataGVImgCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordLibImageDataGVImgCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordMatchDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordMatchDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordNameDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordNameDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordSnapImageDataGVImgCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordSnapImageDataGVImgCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordSourceDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordSourceDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool faceAlarmRecordTimeDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("faceAlarmRecordTimeDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool facePassThruRecordAlarmSourceDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("facePassThruRecordAlarmSourceDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool facePassThruRecordFaceImageDataGVImgCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("facePassThruRecordFaceImageDataGVImgCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool facePassThruRecordPanoImageDataGVImgCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("facePassThruRecordPanoImageDataGVImgCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool facePassThruRecordTimeDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("facePassThruRecordTimeDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   System.Windows.Forms.ImageListStreamer türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Windows.Forms.ImageListStreamer imageList1_ImageStream {
            get {
                object obj = ResourceManager.GetObject("imageList1.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///   {X=242,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point imageList1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("imageList1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordCameraNameDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordCameraNameDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordPlateColorDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordPlateColorDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordPlateImageDataGVImgCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordPlateImageDataGVImgCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordPlateNoDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordPlateNoDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordPlateTypeDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordPlateTypeDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordTimeDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordTimeDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True öğesine benzeyen System.Boolean türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static bool LPRAlarmRecordVehicleColorDataGVTextCol_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LPRAlarmRecordVehicleColorDataGVTextCol.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   {X=357,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point PannelContextMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("PannelContextMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {X=17,Y=17} öğesine benzeyen System.Drawing.Point türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        public static System.Drawing.Point rootOper_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("rootOper.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
